### ISSUE TITLE
RuntimeError: invalid multinomial distribution (sum of probabilities <= 0)

### ISSUE THREAD

**Issue by chenchenchen77** [BorealisAI/tree-cross-attention#1]
Hello, thank you for your open source, I am trying to reproduce your code, but there is this problem, I would like to ask why this is. The only difference between my configuration and your requirement is that torchvision is 0.12.0 (because torch1.11.0 corresponds to 0.12.0-->pip install torch==1.11.0+cu113 torchvision = = 0.12.0 + cu113 torchaudio = = 0.11.0 - extra - index - URL https://download.pytorch.org/whl/cu113)
The command is  python copy_task.py --mode train --expid tca --sequence_length 25
![a2315fbac8b8baad392160023a745a6](https://github.com/BorealisAI/tree-cross-attention/assets/89250978/5012c8fa-5069-43c7-bd5d-18cf143757bf)
![8b68672a07b700ca9a1577eb64ea7d4](https://github.com/BorealisAI/tree-cross-attention/assets/89250978/b8e828f9-131a-4d70-b18f-7af412b20661)
Traceback (most recent call last):
  File "/data/tree-cross-attention-main/copy_task.py", line 302, in <module>
    main()
  File "/data/tree-cross-attention-main/copy_task.py", line 120, in main
    train(args, model)
  File "/data/tree-cross-attention-main/copy_task.py", line 187, in train
    outs = model(batch)
  File "/home/anaconda3/envs/TCA/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "models/retreever.py", line 297, in forward
    tca_encoding, tca_leaf_encoding, entropy, log_action_probs = self.decoder(query_embedding, context_memory_block)
  File "/home/anaconda3/envs/TCA/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/tree-cross-attention-main/models/decoder_modules.py", line 87, in forward
    x_tca, x_tca_leaf, entropy_scores, log_action_probs = self.layer(x, context_memory)
  File "/home/anaconda3/envs/TCA/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/tree-cross-attention-main/models/decoder_modules.py", line 42, in forward
    ) = context_memory.retrieve(query_encodings)
  File "/data/tree-cross-attention-main/models/memory_modules.py", line 235, in retrieve
    self.tree_retrieval(query_data)
  File "/data/tree-cross-attention-main/models/memory_modules.py", line 338, in tree_retrieval
    selected_indices = torch.multinomial(level_search_att_weight_mean_nodes.flatten(0, 1), 1)
RuntimeError: invalid multinomial distribution (sum of probabilities <= 0)

**Comment by leofeng-ca** [comment]
Hi! Thanks for catching that. This issue happens in the rare case that the policy drops all the possible actions. I pushed a 1-line change to set the dropout probability of the policy to 0. That should fix this issue.
